services:
  redis:
    container_name: scramble_dev_redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes

  postgres:
    image: postgres:15
    container_name: scramble_dev_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: scramble
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  redis_data:
  pg_data:
