services:
  redis:
    container_name: scramble_dev_redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes

volumes:
  redis_data:
